# Generated by Django 4.1.1 on 2022-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderId", models.IntegerField()),
                ("userName", models.CharField(max_length=30)),
                ("previousCarModel", models.CharField(max_length=30)),
                ("currentCarModel", models.CharField(max_length=30)),
                ("previousCarNumber", models.CharField(max_length=30)),
                ("currentCarNumber", models.CharField(max_length=30)),
                ("previousServicesName", models.CharField(max_length=30)),
                ("currentServicesName", models.CharField(max_length=30)),
                ("previousServicesPrice", models.CharField(max_length=30)),
                ("currentServicesPrice", models.CharField(max_length=30)),
                ("previousPrice", models.CharField(max_length=30)),
                ("currentPrice", models.CharField(max_length=30)),
                ("isCancelled", models.BooleanField(max_length=30)),
                ("cancelledReason", models.CharField(max_length=30)),
            ],
        ),
    ]
