# Generated by Django 4.1.1 on 2022-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("duration", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
            options={"verbose_name": "service", "verbose_name_plural": "services", },
        ),
    ]
