# Generated by Django 4.1.1 on 2022-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("avatar", models.ImageField(upload_to="")),
                ("location", models.CharField(max_length=200)),
            ],
            options={"verbose_name": "company", "verbose_name_plural": "companies",},
        ),
    ]
