# Generated by Django 4.1.1 on 2022-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("carModel", models.CharField(max_length=30)),
                ("carNumber", models.CharField(max_length=3)),
                ("clientName", models.CharField(max_length=50)),
                ("clientNumber", models.IntegerField()),
                ("isActive", models.BooleanField()),
                ("isCancelled", models.BooleanField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "order", "verbose_name_plural": "orders",},
        ),
    ]
